sudo: required
services:
  - docker
language: node_js
os: linux
cache: yarn
node_js:
  - stable
env:
  - DOCKER_COMPOSE_VERSION: 1.13.0
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - npm run build
  - npm start
  - sleep 10
script:
  - npm test
deploy:
  - provider: npm
    email: anton@mokr.org
    api_key: "$NPM_API_KEY"
    on:
      repo: amokrushin/duk
      tags: true
  - provider: script
    script: TRAVIS_TAG=$TRAVIS_TAG ./docker-deploy.sh $DUK_STORE_TRIGGER_URL $DUK_IMAGE_TRANSFORM_TRIGGER_URL $DUK_UPLOADS_TRIGGER_URL
    skip_cleanup: true
    on:
      repo: amokrushin/duk
      tags: true