version: '3'
services:
  front:
    build: ./services/nginx
    ports:
      - "${PORT}:80"
    expose:
      - "80"
    depends_on:
      - store
      - upload
    networks:
      - duk-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    env_file:
      - .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    expose:
      - "5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASS}
    networks:
      - duk-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - "${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - duk-network
    restart: unless-stopped

  store:
    build: ./tools/nodemon
    volumes:
      - .:/app:ro
      - ${DUK_STORE_DIR}:${DUK_STORE_DIR}
    command: [nodemon, --trace-warnings, --watch, lib, --watch, shared, --watch, services/store, services/store/app.js]
    env_file:
      - .env
    expose:
      - "80"
    environment:
      - AMQP_URL=amqp://${AMQP_USER}:${AMQP_PASS}@rabbitmq/${AMQP_VHOST}
      - REDIS_URL=redis://:${REDIS_PASS}@redis/${REDIS_DB}
    networks:
      - duk-network
    depends_on:
      - rabbitmq
      - redis
    restart: unless-stopped

  upload:
    build: ./tools/nodemon
    volumes:
      - .:/app:ro
    command: [nodemon, --trace-warnings, --watch, lib, --watch, shared, --watch, services/uploads, services/uploads/app.js]
    env_file:
      - .env
    expose:
      - "80"
    networks:
      - duk-network
    depends_on:
      - rabbitmq
      - redis
      - store
    restart: unless-stopped

  image-transform:
    build: ./tools/nodemon
    volumes:
      - .:/app:ro
    command: [nodemon, --trace-warnings, --watch, lib, --watch, shared, --watch, services/image-transform, services/image-transform/app.js]
    env_file:
      - .env
    environment:
      - AMQP_URL=amqp://${AMQP_USER}:${AMQP_PASS}@rabbitmq/${AMQP_VHOST}
      - REDIS_URL=redis://:${REDIS_PASS}@redis/${REDIS_DB}
    networks:
      - duk-network
    depends_on:
      - rabbitmq
      - redis
      - store
    restart: unless-stopped

networks:
  duk-network:
